const nob = {
  regex: '0\\d{4}|[1-5]|[60-89]{2}',
  table: [
    { txt: 'e', plaincode: '1' },
    { txt: 'r', plaincode: '2' },
    { txt: 't', plaincode: '3' },
    { txt: 'n', plaincode: '4' },
    { txt: 's', plaincode: '5' },
    { txt: 'i', plaincode: '60' },
    { txt: 'a', plaincode: '61' },
    { txt: 'l', plaincode: '62' },
    { txt: 'o', plaincode: '63' },
    { txt: 'd', plaincode: '64' },
    { txt: 'g', plaincode: '65' },
    { txt: 'k', plaincode: '66' },
    { txt: 'm', plaincode: '67' },
    { txt: 'v', plaincode: '68' },
    { txt: 'p', plaincode: '69' },
    { txt: 'f', plaincode: '70' },
    { txt: 'u', plaincode: '71' },
    { txt: 'h', plaincode: '72' },
    { txt: 'å', plaincode: '73' },
    { txt: 'b', plaincode: '74' },
    { txt: 'j', plaincode: '75' },
    { txt: 'ø', plaincode: '76' },
    { txt: 'y', plaincode: '77' },
    { txt: 'c', plaincode: '78' },
    { txt: 'æ', plaincode: '79' },
    { txt: 'w', plaincode: '80' },
    { txt: 'x', plaincode: '81' },
    { txt: 'z', plaincode: '82' },
    { txt: 'q', plaincode: '83' },
    { txt: '*', plaincode: '84' },
    { txt: '@', plaincode: '85' },
    { txt: '#', plaincode: '86' },
    { txt: '+', plaincode: '87' },
    { txt: '-', plaincode: '88' },
    { txt: '/', plaincode: '89' },
    { txt: '0', plaincode: '900' },
    { txt: '1', plaincode: '901' },
    { txt: '2', plaincode: '902' },
    { txt: '3', plaincode: '903' },
    { txt: '4', plaincode: '904' },
    { txt: '5', plaincode: '905' },
    { txt: '6', plaincode: '906' },
    { txt: '7', plaincode: '907' },
    { txt: '8', plaincode: '908' },
    { txt: '9', plaincode: '909' },
    { txt: '.', plaincode: '91' },
    { txt: ':', plaincode: '92' },
    { txt: '\'', plaincode: '93' },
    { txt: '!', plaincode: '94' },
    { txt: '(', plaincode: '95' },
    { txt: ')', plaincode: '96' },
    { txt: '=', plaincode: '97' },
    { txt: '?', plaincode: '98' },
    { txt: ' ', plaincode: '99' }
  ]
}
export { nob }
